### ISSUE TITLE
Program does nothing when run without arguments

### ISSUE THREAD

**Issue by ctsrc** [birkenfeld/fddf#18]
When `fddf` is run without arguments, nothing observable happens. No output.

IMO it would be preferable to have it act in either of the following ways:

* Either, do like `ls` and use the current working directory when no argument is provided. This makes the most sense for `fddf` IMO since `fddf` does not modify any files so it is safe to run `fddf` somewhere by accident.

* Or, make the roots argument required (see https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.required and press the pluss sign on the side to expand the description) so that clap reports an error to the user when `fddf` is run without any arguments. Personally I think making the argument required would *not* be as great because it means more typing.

**Comment by birkenfeld** [comment]
Agreed, will implement this with option 1.
