### ISSUE TITLE
error: no method named `ino` found for type `walkdir::DirEntry` in the current scope

### ISSUE THREAD

**Issue by Boscop** [birkenfeld/fddf#3]
```
error[E0599]: no method named `ino` found for type `walkdir::DirEntry` in the current scope
   --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\fddf-1.3.0\src\main.rs:260:68
    |
260 |                                         if inodes.insert(dir_entry.ino())
{
    |                                                                    ^^^
 
error: aborting due to previous error(s)
```

**Comment by birkenfeld** [comment]
Thanks for the report. Is this on Windows? I'll have to make this check conditional...

**Comment by Boscop** [comment]
Yes, on Windows.
Btw, maybe you can use this:
https://doc.rust-lang.org/std/path/struct.Path.html#method.symlink_metadata
`path.symlink_metadata()?.file_type().is_symlink()`
and get the target with `path.canonicalize()`.

**Comment by birkenfeld** [comment]
Well, the point here is to avoid counting two or more hardlinked files as duplicates.

On Windows hardlinks, while possible, are pretty uncommon, so I don't think it'll matter to leave out this check there.

**Comment by Boscop** [comment]
But maybe it's still useful for Windows soft symlinks?

**Comment by birkenfeld** [comment]
`walkdir` is already supposed to ignore symlinks with `follow_links(false)`.
