### ISSUE TITLE
Unicode filenames are not printed correctly

### ISSUE THREAD

**Issue by Boscop** [birkenfeld/fddf#9]
```
> fddf .
Size 16700 bytes:
    .\sekaihana.mid
    .\??????????.mid

Size 15426 bytes:
    .\????????????.mid
    .\yasasisa.mid
```

Btw, the first filename is 世界にひとつだけの花.mid and the second one is やさしさにつつまれたなら.mid.

When I do [`cmd /K chcp 65001`](https://stackoverflow.com/a/18439832/7488353) and run fddf, I get:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Err
or { repr: Os { code: 31, message: "A device attached to the system is not funct
ioning." } }', src\libcore\result.rs:860
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: BaseThreadInitThunk
thread 'main' panicked at 'WaitGroup explicitly poisoned!', .cargo\registry\src\
github.com-1ecc6299db9ec823\scoped-pool-1.0.0\src\lib.rs:457
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: BaseThreadInitThunk
```

**Comment by manfredlotz** [comment]
Hm, I'm a bit late here. 

But on my system (Linux and a btrfs file system) I get, for example,
% fddf testdir 
Size 5 bytes:
    testdir/世界にひとつだけの花.mid
    testdir/second.mid

which looks good.

Are you on Windows?

**Comment by Boscop** [comment]
Yes, Win 8.1

**Comment by manfredlotz** [comment]
Unfortunately, I have no access to any Windows to test this.

**Comment by birkenfeld** [comment]
Hmm, this is using `Path::display()` which is meant to be used for this.

I don't think fddf is at fault if that doesn't work - you might need to report a bug with the Rust stdlib.
